name: Build and Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify environment
      run: npm run verify
      
    - name: Build project
      run: npm run build
      
    - name: Package project
      run: npm run package
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gamebet-build-${{ github.sha }}
        path: |
          build/
          package/
        retention-days: 30
        
    - name: Upload Android packages
      uses: actions/upload-artifact@v3
      with:
        name: gamebet-android-${{ github.sha }}
        path: |
          package/android/
        retention-days: 90

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: gamebet-build-${{ github.sha }}
        
    - name: Verify build integrity
      run: |
        echo "Verifying build artifacts..."
        ls -la build/
        ls -la package/
        
        # Check if required files exist
        test -f build/GameBet.aab
        test -f build/GameBet.apk
        test -f build/assetlinks.json
        test -f build/manifest.json
        test -f build/checksums.json
        
        echo "✅ Build verification passed"